const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');
const {openStore}=require('../inspections.cjs');const {dailyBackup,verify}=require('../scripts/daily-backup.cjs');const {backup}=require('../scripts/backup.cjs');
const DAY=86400000,now=Date.parse('2026-10-09T22:00:00Z');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'fornalha-retention-')),source=path.join(dir,'source'),dest=path.join(dir,'backups');fs.mkdirSync(source);const s=openStore(source);s.close();fs.writeFileSync(path.join(source,'admin.json'),JSON.stringify({version:1,salt:'a'.repeat(32),hash:'b'.repeat(128)}));t.after(()=>{assert.equal(path.dirname(path.resolve(dir)),path.resolve(os.tmpdir()));assert.match(path.basename(dir),/^fornalha-retention-/);fs.rmSync(dir,{recursive:true,force:true});});return {source,dest};}
test('retenção exclui somente cópias próprias com mais de 30 dias e preserva limite e backup atual',t=>{const {source,dest}=setup(t);const old=dailyBackup(source,dest,{now:now-31*DAY}).destination;const boundary=dailyBackup(source,dest,{now:now-30*DAY}).destination;const current=dailyBackup(source,dest,{now});assert.equal(fs.existsSync(old),false);assert.equal(fs.existsSync(boundary),true);verify(current.destination);assert.deepEqual(current.removed,[path.basename(old)]);});
test('falha de backup ou de integridade não apaga cópias anteriores',t=>{const {source,dest}=setup(t),old=dailyBackup(source,dest,{now:now-40*DAY}).destination;assert.throws(()=>dailyBackup(source,dest,{now,makeBackup(){throw new Error('disco cheio');}}),/disco cheio/);assert.ok(fs.existsSync(old));assert.throws(()=>dailyBackup(source,dest,{now,makeBackup(s,d){backup(s,d);fs.writeFileSync(path.join(d,'frota.sqlite'),'corrompido');}}));assert.ok(fs.existsSync(old));assert.ok(!fs.existsSync(path.join(dest,'.fornalha-backup.lock')));});
test('preserva backup manual, pastas com arquivos extras e subpastas, e marcadores inválidos',t=>{const {source,dest}=setup(t),extra=dailyBackup(source,dest,{now:now-50*DAY}).destination;fs.writeFileSync(path.join(extra,'documento.txt'),'não remover');const nested=dailyBackup(source,dest,{now:now-49*DAY}).destination;fs.mkdirSync(path.join(nested,'outros'));const manual=path.join(dest,'2026-01-01');backup(source,manual);const forged=path.join(dest,'FFC-outro');fs.mkdirSync(forged);fs.writeFileSync(path.join(forged,'retention.json'),'{}');dailyBackup(source,dest,{now});for(const p of [extra,nested,manual,forged])assert.ok(fs.existsSync(p));assert.equal(fs.readFileSync(path.join(extra,'documento.txt'),'utf8'),'não remover');});
test('trava impede concorrência e destino dentro do banco é recusado',t=>{const {source,dest}=setup(t);fs.mkdirSync(dest);fs.writeFileSync(path.join(dest,'.fornalha-backup.lock'),'');assert.throws(()=>dailyBackup(source,dest,{now}),/execução/);assert.throws(()=>dailyBackup(source,path.join(source,'copies'),{now}),/dentro dos dados/);});
test('junções não são seguidas durante limpeza',t=>{const {source,dest}=setup(t);dailyBackup(source,dest,{now});const outside=path.join(path.dirname(source),'outside');fs.mkdirSync(outside);fs.writeFileSync(path.join(outside,'protegido.txt'),'seguro');fs.symlinkSync(outside,path.join(dest,'FFC-link'),'junction');dailyBackup(source,dest,{now:now+DAY});assert.equal(fs.readFileSync(path.join(outside,'protegido.txt'),'utf8'),'seguro');});
