const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');const {openStore}=require('../inspections.cjs');const {create}=require('../drafts.js');
function record(){return {version:2,id:crypto.randomUUID(),driverId:1,driver:'Motorista 01 · exemplo',vehicle:0,vehicleName:'Master',refrigerated:true,type:'Saída',km:100,temperature:-9,inspectedAt:'2026-10-09T10:00:00Z',answers:Object.fromEntries(['pneus','freios','luzes','oleo','motor','avarias','seguranca','frio'].map(id=>[id,'OK'])),notes:{},levels:{}};}
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'fornalha-management-'));let s=openStore(dir);t.after(()=>{s.close();assert.equal(path.dirname(dir),os.tmpdir());assert.ok(path.basename(dir).startsWith('fornalha-management-'));fs.rmSync(dir,{recursive:true,force:true});});return {get s(){return s;},restart(){s.close();s=openStore(dir);}};}
const now=Date.parse('2026-10-10T12:00:00Z');
test('correção preserva original, reenvio idempotente, histórico e quilometragem após reinício',t=>{const c=setup(t),r=record();c.s.save(r,now);c.s.correct({id:r.id,revision:0,action:'km',km:123,reason:'Leitura digitada incorretamente'},now);assert.equal(c.s.save(r,now).duplicate,true);assert.equal(c.s.catalog().drivers[0].trip.pending.km,123);c.restart();assert.equal(c.s.mileage(0).vehicle.lastReading.km,123);const row=c.s.list('2026-10-09').records[0];assert.equal(row.corrections[0].before.km,100);assert.equal(row.km,123);assert.throws(()=>c.s.correct({id:r.id,revision:0,action:'km',km:130,reason:'Concorrência'},now),/alterado/);});
test('corrigir veículo atualiza retorno exigido e filtros; cancelamento libera sem apagar auditoria',t=>{const {s}=setup(t),r=record();s.save(r,now);assert.throws(()=>s.correct({id:r.id,revision:0,action:'vehicle',vehicle:4,reason:'Troca'},now),/refrigeração/);s.correct({id:r.id,revision:0,action:'vehicle',vehicle:1,reason:'Veículo errado'},now);assert.equal(s.catalog().drivers[0].trip.pending.vehicle,1);assert.equal(s.list('2026-10-09','2026-10-09',0).total,0);assert.equal(s.list('2026-10-09','2026-10-09',1).total,1);s.correct({id:r.id,revision:1,action:'cancel',reason:'Teste'},now);assert.equal(s.catalog().drivers[0].trip.pending,null);assert.equal(s.list('2026-10-09').total,0);assert.equal(s.list('2026-10-09').records[0].cancelled,true);assert.equal(s.mileage(1).readings.length,0);assert.equal(s.save(r,now).duplicate,true);assert.equal(s.catalog().drivers[0].trip.pending,null);s.save({...record(),inspectedAt:'2026-10-09T11:00:00Z'},now);});
test('não cancela movimento encerrado; ocorrência mantém situação e histórico sem alterar frequência',t=>{const c=setup(t),r=record();c.s.save(r,now);c.s.updateOccurrence({id:r.id,item:'Temperatura',revision:0,status:'Em avaliação',note:'Oficina consultada'},now);c.s.updateOccurrence({id:r.id,item:'Temperatura',revision:1,status:'Resolvido',note:'Equipamento revisado'},now);assert.throws(()=>c.s.updateOccurrence({id:r.id,item:'Temperatura',revision:1,status:'Aberto',note:'Desatualizado'},now),/alterada/);c.s.save({...r,id:crypto.randomUUID(),type:'Retorno',inspectedAt:'2026-10-09T18:00:00Z',temperature:-16},now);assert.throws(()=>c.s.correct({id:r.id,revision:0,action:'cancel',reason:'Teste'},now),/pendente/);c.restart();const report=c.s.list('2026-10-09');assert.equal(report.frequency[0].count,1);assert.equal(report.occurrences[0].status,'Resolvido');assert.equal(report.occurrences[0].history.length,2);});
test('rascunho serializa gravações, preserva fotos e limpar aguarda salvamentos anteriores',async()=>{let saved;const writes=[];const storage={read:async()=>saved,write:async v=>{await new Promise(r=>setTimeout(r,5));saved=v;writes.push(v);}};const d=create(storage),a={step:2,photos:[{data:'foto'}],km:'100'};const first=d.save(a);a.km='999';const second=d.save({...a,step:3});await Promise.all([first,second]);assert.equal(writes[0].km,'100');assert.equal((await create(storage).read()).step,3);assert.equal(saved.photos[0].data,'foto');const third=d.save(a);await d.clear();await third;assert.equal(await d.read(),null);});
test('falha de armazenamento é informada e próximo salvamento pode recuperar',async()=>{let fail=true,value;const d=create({read:async()=>value,write:async v=>{if(fail)throw new Error('disco');value=v;}});await assert.rejects(d.save({step:1}),/disco/);fail=false;await d.save({step:2});assert.equal((await d.read()).step,2);});
